# Generated by Django 4.0.4 on 2022-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=50)),
                ('Puesto', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Campeonatos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Resultado', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Escuelitas',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('identificador_de_clase', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=50)),
                ('Deporte', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
