# Generated by Django 4.0.3 on 2022-04-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
