# Generated by Django 4.0.3 on 2022-05-04 17:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppClub', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteos_nuevos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('post', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Autoridades',
        ),
        migrations.DeleteModel(
            name='Campeonatos',
        ),
        migrations.DeleteModel(
            name='Escuelitas',
        ),
        migrations.DeleteModel(
            name='Socios',
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='imagen',
        ),
        migrations.AddField(
            model_name='avatar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
